### ISSUE TITLE
Help to resize the software window

### ISSUE THREAD

**Issue by Sprintel82** [vospascal/pedal-gui#2]
Hi, I want to use your software, for some reason, maybe because of my screen, but I can't modify the size of the software window, which prevents me from saving calibrations and settings, since I can't see the bottom of the options.

**Comment by Toughbeard** [comment]
Hello, I am sorry I just saw your message.  Please join the HuanTV discord channel where there is huge community, including the author, that will help you with the software problem.  I just check once every 2 months to fix the English in the documentation.

**Comment by pascalvos** [comment]
i sugest using the webversion for this

**Comment by vospascal** [comment]
closing cause not going to add resizing to it
