### ISSUE TITLE
High CPU utilization 

### ISSUE THREAD

**Issue by utcoolguy** [vospascal/pedal-gui#3]
Hi, i am using your software provided by simforge. i have noticed that the when open the program used high amounts of cpu power. for my specific CPU it consumes 10-20% of the CPU resources. this seems very high and impacts the game fps when the program is open.

**Comment by vospascal** [comment]
could be :) because it shows live data.
you dont need to have this open to race, i wouldnt.
you set your settings and there saved on the pedals program is only to configure it.
close program and if you want to change something open it again
